pipeline {
    agent any

    tools {
            // Install the Maven version configured as "M3" and add it to the path.
            maven "m3"
        }

    parameters {
        gitParameter branchFilter: 'origin/(.*)', defaultValue: 'develop', name: 'BRANCH', type: 'PT_BRANCH'
        choice(name: 'BROWSER', choices: ['chrome', 'firefox'], description: 'Select browser')
        choice(name: 'SUITE', choices: ['smoke', 'regression', 'negative'], description: 'Choose suite to run')
        booleanParam(name: 'IS_HEADLESS', defaultValue: false, description: 'Headless mode')
    }

    triggers {
            parameterizedCron('''
            0 9 * * 1,3,5 %SUITE=smoke;BROWSER=Chrome;
            00 23 1-31/2 * *  %SUITE=regression;BROWSER=firefox;
            0 9 * * 1,2,5 %SUITE=negative;BROWSER=Chrome;
            ''')
        }

    tools {
        maven "m3"
    }

    stages {
        stage('Run tests') {
            steps {
            git branch: "${params.BRANCH}", url: 'https://github.com/TatyanaBogdanovich/Diplome_Monkkee_QA26_TanyaBogdanovich.git'
            bat "mvn -Dmaven.test.failure.ignore=true -Dbrowser=${params.BROWSER} -Dheadless=${params.IS_HEADLESS} -DsuiteName=${params.SUITE} clean test"
            }

            post {
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                }
            }
        }

        stage('Generate Allure report') {
            steps {
                allure includeProperties: false, report: 'target/allure-report', results: [[path: 'target/allure-results']]
            }
        }
    }
}